#!/usr/bin/env python3
"""Unit tests for file edit permission checking in check_agent_rules.py."""

from pathlib import Path
import tempfile
from src.check_rules import check_path, check_paths


class TestDeniedPaths:
    """Test the check_path function for matching paths with deny list."""

    def test_denied_path_basic(self):
        """Test that a relative file is denied when resolved from rules dir."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            test_file = base_dir / "protected.txt"
            
            deny_list = [
                {
                    "path": "protected.txt",
                    "reason": "Do not edit this file",
                }
            ]

            status, reason = check_path(str(test_file), deny_list, base_dir)

            assert status == "deny"
            assert reason == "Do not edit this file"

    def test_denied_without_reason(self):
        """Test that denied entry without reason still works."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            test_file = base_dir / "protected.txt"

            deny_list = [{"path": "protected.txt"}]

            status, reason = check_path(str(test_file), deny_list, base_dir)

            assert status == "deny"
            assert reason is None

    def test_denied_in_subdir(self):
        """Test that deny list can specify a file in a subdirectory."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)

            src_dir = base_dir / "src"
            test_file = src_dir / "protected.txt"

            deny_list = [{"path": "src/protected.txt"}]

            status, _ = check_path(str(test_file), deny_list, base_dir)
            assert status == "deny"

    def test_deeply_nested_paths(self):
        """Test that deeply nested relative paths are resolved correctly."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)

            deep_dir = base_dir / "a" / "b" / "c" / "d"
            deep_file = deep_dir / "nested.py"

            deny_list = [{"path": "a/b/c/d/nested.py"}]

            status, _ = check_path(str(deep_file), deny_list, base_dir)
            assert status == "deny"

    def test_denied_directory(self):
        """Test that files in denied directory are denied."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)

            src_dir = base_dir / "src"
            test_file = src_dir / "somefile"

            deny_list = [{"path": "src"}]

            status, _ = check_path(str(test_file), deny_list, base_dir)
            assert status == "deny"

    def test_denied_absolute_path(self):
        """Test that denied absolute path matches correctly."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)

            tests_dir = base_dir / "tests"
            test_file = tests_dir / "test_check_agent_rules.py"
            absolute_path = str(test_file.resolve())
            some_other_dir = base_dir / "other"

            deny_list = [{"path": absolute_path}]

            # Should match using absolute path regardless of rules directory
            status, _ = check_path(absolute_path, deny_list, some_other_dir)
            assert status == "deny"

    def test_different_files_with_same_name(self):
        """Test that files with same name in different directories are distinguished."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)

            src_dir = base_dir / "src"
            first_file = src_dir / "config.yaml"

            other_dir = base_dir / "other"
            second_file = other_dir / "config.yaml"

            third_file = base_dir / "config.yaml"

            deny_list = [{"path": "src/config.yaml"}]

            # src/config.yaml should be denied
            status, _ = check_path(str(first_file), deny_list, base_dir)
            assert status == "deny"

            # other/config.yaml should be allowed
            status, _ = check_path(str(second_file), deny_list, base_dir)
            assert status is None

            # config.yaml should be allowed
            status, _ = check_path(str(third_file), deny_list, base_dir)
            assert status is None

    def test_allowed_file(self):
        """Test that files not in denied list are allowed."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)

            deny_list = [{"path": "config.yaml"}]

            status, _ = check_path("readme.md", deny_list, base_dir)
            assert status is None

    def test_empty_deny_list(self):
        """Test that empty denied list allows all files."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            status, _ = check_path("any_file.txt", [], base_dir)
            assert status is None

    def test_relative_path_resolution_from_base_dir(self):
        """Test that relative paths in deny_edits are resolved from rules directory."""
        with tempfile.TemporaryDirectory() as tmpdir:
            project1 = Path(tmpdir) / "project1"
            project2 = Path(tmpdir) / "project2"

            config1 = project1 / "config.yaml"
            config2 = project2 / "config.yaml"

            base_dir = project1
            deny_list = [{"path": "config.yaml"}]

            # config.yaml in project1 should be denied (resolved from rules dir)
            status, _ = check_path(str(config1), deny_list, base_dir)
            assert status == "deny"

            # config.yaml in project2 should be allowed (different absolute path)
            status, _ = check_path(str(config2), deny_list, base_dir)
            assert status is None

class TestProcessEditingTool:
    """Test the process_editing_tool function."""

    def test_denied_path(self):
        """Test that editing a single denied file returns deny status and reason."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            rules_file = base_dir / "agent-rules.yaml"
            test_file = base_dir / "protected.txt"

            deny_list = [
                {
                    "path": "protected.txt",
                    "reason": "Do not edit this file",
                }
            ]

            status, reason = check_paths([str(test_file)], {"deny_edits": deny_list}, base_dir)

            assert status == "deny"
            assert reason == "Do not edit this file"

    def test_multiple_paths_all_allowed(self):
        """Test that editing multiple allowed files returns None status."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            rules_file = base_dir / "agent-rules.yaml"
            rules_file.touch()

            denied_edits = [{"path": "agent-rules.yaml"}]

            status, reason = check_paths(["file1.py", "file2.py", "file3.py"], {"deny_edits": denied_edits}, base_dir)

            assert status is None
            assert reason is None

    def test_multiple_paths_one_denied(self):
        """Test that one denied file in a list denies the operation."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            rules_file = base_dir / "agent-rules.yaml"
            rules_file.touch()

            protected_file = base_dir / "protected.py"
            protected_file.touch()

            denied_edits = [
                {
                    "path": "protected.py",
                    "reason": "Protected file"
                }
            ]

            status, reason = check_paths(["file1.py", str(protected_file), "file3.py"], {"deny_edits": denied_edits}, base_dir)

            assert status == "deny"
            assert reason == "Protected file"
