#!/usr/bin/env python3
"""Unit tests for file edit permission checking in agent_rules.py."""

import sys
from pathlib import Path
import pytest
import json
import tempfile
import os

# Add parent directory to path to import agent_rules
sys.path.insert(0, str(Path(__file__).parent.parent))

from agent_rules import check_path, process_editing_tool


class TestDeniedPaths:
    """Test the check_path function for matching paths with deny list."""

    def test_denied_path_basic(self):
        """Test that a relative file is denied when resolved from rules dir."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            test_file = base_dir / "protected.txt"
            
            deny_list = [
                {
                    "path": "protected.txt",
                    "reason": "Do not edit this file",
                    "context": "Ask operator for changes if needed",
                }
            ]

            is_denied, details = check_path(str(test_file), deny_list, base_dir)

            assert is_denied is True
            assert details.get("reason") == "Do not edit this file"
            assert details.get("context") == "Ask operator for changes if needed"

    def test_denied_without_reason(self):
        """Test that denied entry without reason still works."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            test_file = base_dir / "protected.txt"
            
            deny_list = [{"path": "protected.txt"}]

            is_denied, details = check_path(str(test_file), deny_list, base_dir)

            assert is_denied is True
            assert details == {}

    def test_denied_in_subdir(self):
        """Test that deny list can specify a file in a subdirectory."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            
            src_dir = base_dir / "src"
            test_file = src_dir / "protected.txt"
            
            deny_list = [
                {"path": "src/protected.txt"}
            ]

            is_denied, _ = check_path(str(test_file), deny_list, base_dir)
            assert is_denied is True

    def test_deeply_nested_paths(self):
        """Test that deeply nested relative paths are resolved correctly."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            
            # Create nested directory structure
            deep_dir = base_dir / "a" / "b" / "c" / "d"
            deep_file = deep_dir / "nested.py"
            
            deny_list = [{"path": "a/b/c/d/nested.py"}]
            
            is_denied, _ = check_path(str(deep_file), deny_list, base_dir)
            assert is_denied is True

    def test_denied_directory(self):
        """Test that files in denied directory are denied."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            
            src_dir = base_dir / "src"
            test_file = src_dir / "somefile"
            
            deny_list = [
                {"path": "src"}
            ]

            is_denied, _ = check_path(str(test_file), deny_list, base_dir)
            assert is_denied is True


    def test_denied_absolute_path(self):
        """Test that denied absolute path matches correctly."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            
            tests_dir = base_dir / "tests"
            test_file = tests_dir / "test_agent_rules.py"
            absolute_path = str(test_file.resolve())
            some_other_dir = base_dir / "other"
            
            deny_list = [
                {"path": absolute_path}
            ]

            # Should match using absolute path regardless of rules directory
            is_denied, _ = check_path(absolute_path, deny_list, some_other_dir)
            assert is_denied is True

    def test_different_files_with_same_name(self):
        """Test that files with same name in different directories are distinguished."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            
            # Create a config.yaml in one subdirectory
            src_dir = base_dir / "src"
            first_file = src_dir / "config.yaml"
            
            # Create a different config.yaml in another directory
            other_dir = base_dir / "other"
            second_file = other_dir / "config.yaml"

            # Create a config.yaml in base directory
            third_file = base_dir / "config.yaml"
            
            deny_list = [{"path": "src/config.yaml"}]

            # src/config.yaml should be denied
            is_denied, _ = check_path(str(first_file), deny_list, base_dir)
            assert is_denied is True
            
            # other/config.yaml should be allowed
            is_denied, _ = check_path(str(second_file), deny_list, base_dir)
            assert is_denied is False

            # config.yaml should be allowed
            is_denied, _ = check_path(str(third_file), deny_list, base_dir)
            assert is_denied is False

    def test_allowed_file(self):
        """Test that files not in denied list are allowed."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            
            deny_list = [
                {"path": "config.yaml"}
            ]

            is_denied, _ = check_path("readme.md", deny_list, base_dir)
            assert is_denied is False

    def test_empty_deny_list(self):
        """Test that empty denied list allows all files."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            is_denied, _ = check_path("any_file.txt", [], base_dir)
            assert is_denied is False


    def test_relative_path_resolution_from_base_dir(self):
        """Test that relative paths in deny_edits are resolved from rules directory."""
        with tempfile.TemporaryDirectory() as tmpdir:
            # Create two separate projects 
            project1 = Path(tmpdir) / "project1"
            project2 = Path(tmpdir) / "project2"
            
            # Create config.yaml in both projects
            config1 = project1 / "config.yaml"
            config2 = project2 / "config.yaml"
            
            # Rules file is in project1
            base_dir = project1
            deny_list = [{"path": "config.yaml"}]
            
            # config.yaml in project1 should be denied (resolved from rules dir)
            is_denied, _ = check_path(str(config1), deny_list, base_dir)
            assert is_denied is True
            
            # config.yaml in project2 should be allowed (different absolute path)
            is_denied, _ = check_path(str(config2), deny_list, base_dir)
            assert is_denied is False

class TestProcessEditingTool:
    """Test the process_editing_tool function and its JSON output."""

    def test_denied_path(self, capsys):
        """Test that editing a single denied file is denied."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            rules_file = base_dir / "agent-rules.yaml"
            test_file = base_dir / "protected.txt"
            
            deny_list = [
                {
                    "path": "protected.txt",
                    "reason": "Do not edit this file",
                    "context": "Ask operator for changes if needed",
                }
            ]

            args = {"path": str(test_file)}

            result = process_editing_tool(args, {"deny_edits": deny_list}, rules_file)

            assert result is True
            captured = capsys.readouterr()
            output = json.loads(captured.out)["hookSpecificOutput"]

            assert output["hookEventName"] == "PreToolUse"
            assert output["permissionDecision"] == "deny"
            assert output["permissionDecisionReason"] == "Do not edit this file"
            assert output["additionalContext"] == "Ask operator for changes if needed"

    def test_multiple_paths_all_allowed(self, capsys):
        """Test that editing multiple allowed files returns False."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            rules_file = base_dir / "agent-rules.yaml"
            rules_file.touch()
            
            denied_edits = [{"path": "agent-rules.yaml"}]
            args = {"paths": ["file1.py", "file2.py", "file3.py"]}

            result = process_editing_tool(args, {"deny_edits": denied_edits}, rules_file)

            assert result is False
            captured = capsys.readouterr()
            assert captured.out == ""

    def test_multiple_paths_one_denied(self, capsys):
        """Test that one denied file in a list denies the operation."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base_dir = Path(tmpdir)
            rules_file = base_dir / "agent-rules.yaml"
            rules_file.touch()
            
            protected_file = base_dir / "protected.py"
            protected_file.touch()
            
            denied_edits = [
                {
                    "path": "protected.py",
                    "reason": "Protected file"
                }
            ]
            args = {"paths": ["file1.py", str(protected_file), "file3.py"]}

            result = process_editing_tool(args, {"deny_edits": denied_edits}, rules_file)

            assert result is True
            captured = capsys.readouterr()
            output = json.loads(captured.out)["hookSpecificOutput"]

            assert output["hookEventName"] == "PreToolUse"
            assert output["permissionDecision"] == "deny"
            assert output["permissionDecisionReason"] == "Protected file"
